# [Dockerfile.fast]
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-noble-chiseled
WORKDIR /app
# 复制主程序并赋权 
COPY --chmod=755 ./docker-build/BoomApi ./BoomApi
# 声明挂载点 
VOLUME /data

EXPOSE 8080
ENTRYPOINT ["./BoomApi"]