# 修正：将 jammy 改为 noble
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-noble-chiseled
WORKDIR /app

# 从 GitHub Actions 构建产物中复制
COPY ./docker-build/BoomApi .
# 复制静态资源
COPY src/wwwroot ./wwwroot

EXPOSE 8080
ENTRYPOINT ["./BoomApi"]